platform: x64
environment:
  nodejs_version: "10"

cache:
  - "%LOCALAPPDATA%\\Yarn"

install:
  - ps: Install-Product node 12
  - yarn install

build_script:
  - yarn make --arch=ia32,x64

artifacts:
  - path: out\make
