version: 2
jobs:
  build-linux:
    docker:
      - image: circleci/node:lts

    working_directory: ~/repo

    steps:
      - run: sudo apt-get update && sudo apt-get install -y fakeroot rpm
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-linux-{{ checksum "package.json" }}
            - v1-dependencies-linux-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-linux-{{ checksum "package.json" }}

      - run: yarn make
      - store_artifacts:
          path: out/make

# lol nvm, circleci mac is not free
#  build-macos:
#    macos:
#      xcode: 11.6.0
#    steps:
#      - checkout
#
#      - restore_cache:
#          keys:
#            - v1-dependencies-macos-{{ checksum "package.json" }}
#            - v1-dependencies-macos-
#
#      - run: yarn install
#
#      - save_cache:
#          paths:
#            - node_modules
#          key: v1-dependencies-macos-{{ checksum "package.json" }}
#
#      - run: yarn make
#      - store_artifacts:
#          path: out/make

workflows:
  version: 2
  build:
    jobs:
      - build-linux
#      - build-macos
